apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 1.1.1.1
    path: /nfs/data

