apiVersion: v1
kind: LimitRange
metadata:
  name: limit-resources
spec:
  limits:
  - defaultRequest:
      cpu: 50m 
      memory: 5Mi 
    default: 
      cpu: 1 
      memory: 1Gi
    type: Container
