apiVersion: v1
kind: Pod
metadata:
  name: testpod-limit-2
spec:
  containers:
  - image: smlinux/appjs
    name: test
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 10Mi
