apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deployment
spec:
  selector:
    matchLabels:
      app: auto-web
  replicas: 2
  template:
    metadata:
      labels:
        app: auto-web
    spec:
      containers:
      - name: c1
        image: k8s.gcr.io/ubuntu-slim:0.1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        command: ["/bin/sh"]
        args: ["-c", "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"]

