apiVersion: batch/v1
kind: Job
metadata:
  name: centos-job
spec:
  selector:
    matchLabels:
      app: backup
  template:
    metadata:
      labels:
        app: backup
    spec:
      containers:
      - name: centos-container
        image: centos:7
        command:
        - /bin/bash
        - -c
        - for i in $(seq 10) ; do echo $i; sleep 10 ; done
      restartPolicy: Never
  backoffLimit: 6
  completions: 1
  parallelism: 1
