apiVersion: v1
kind: Pod
metadata:
  name: testpod-limit-1
spec:
  containers:
  - image: smlinux/appjs
    name: test
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: 20Mi
        cpu: 200m
      requests:
        memory: 256Mi
        cpu: 100m
