apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    project: Happy-Web
    service: web
    version: "0.1"
  template:
    metadata:
      name: nginx
      labels:
        project: Happy-Web
        service: web
        version: "0.1"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
