#!/bin/bash
cat <<EOF | kubectl apply -f - &> /dev/null
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: newpods
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: busybox
  template:
    metadata:
      labels:
         tier: busybox
    spec:
      containers:
      - command:
        - sleep
        - "1000"
        image: busybox
        imagePullPolicy: Always
        name: busybox
      nodeName: node1.example.com
---
EOF
